DEV:
  host: dev-events-broker-id-1.dev.in:9092
TST:
  host: tst-events-broker-id-1.tst.in:9092
UAT:
  host: uat-events-broker-id-1.uat.in:9092

DEFAULT:
  default_environment: DEV
  topics:
    - topic 1
    - topic 2
