DEV:
  host: dev-events-broker-id-1.dev-sicredi.in:9092
TST:
  host: tst-events-broker-id-1.tst-sicredi.in:9092
UAT:
  host: uat-events-broker-id-1.uat-sicredi.in:9092

DEFAULT:
  default_environment: DEV
  topics:
    - conecta-manual-notification-message
    - conecta-manual-notification-message
    - conecta-manual-notification-message
